version: '3.8'

services:
  # Spring Boot Application
  app:
    build: .
   #   context: .
     # dockerfile: Dockerfile
    container_name: url-scrapping
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis

  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: cedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
volumes:
  redis-data:
    driver: local
# Volumes for persistent data storage
